### ISSUE TITLE
Use && or || in a command

### ISSUE THREAD

**Issue by bilby91** [xeger/backticks#16]
I'm using `backticks` for the `docker-compose` gem and I'm having trouble when invoking a command like this:

```
args1 = ["ls", "-lat", "/", "||", "ls", "-lat", "/"]
arg2 = ["ls", "-lat", "/", "&&", "ls", "-lat", "/"]

shell = Backticks::Runner.new(buffered: [:stdout, :stderr], interactive: true)

cmd1 = shell.run(*args1).join
p cmd1.captured_output
p cmd1.status 

cmd2 = shell.run(*args2).join
p cmd2.captured_output
p cmd2.status 
```

Exit status is always 1. Any ideas ? 

Thanks!

**Comment by xeger** [comment]
Hmm; yes. `&&` and `||` are shell programming constructs that are only available if you run a proper shell (`bash`, `sh`, or so forth) and then give that shell a command to run.

Backticks uses Ruby's `Kernel.spawn` method to run the child process. Spawn has a [dual personality](https://ruby-doc.org/core-2.2.0/Process.html#method-c-spawn); if you give it a single positional String parameter, then it uses your standard shell to run that command. If you give many Strings, or if you give it an array of Strings, then it avoids using the shell and executes the specified binary directly, passing the additional strings as the `argv` to that binary. This is a low-level technique but it has a lot of benefits vs. using the shell.

I built Backticks primarily with the low-level use case in mind because the shell can make it hard to do low-level I/O. The documentation of `Backticks::Runnner#run` also implies that you can _only_ pass an array as the `argv` which would imply that it is impossible to use the "shell" form of spawn. However, if you [look at the source](https://github.com/xeger/backticks/blob/master/lib/backticks/runner.rb#L134), we pass argv as a glob to `Kernel#spawn` .... so, as an undocumented feature, I believe you _can_ do what you want with Backticks; you just need to be careful to only pass 1 argument to run, a `String` that has the entirety of your command:

`shell.run('ls -lat / || ls -lat /').join`

**Comment by xeger** [comment]
Another solution would be to specifically invoke the shell:

```
runner.run('/bin/sh', '-c', 'ls -lat / || ls -lat /')
```

This has the advantage that it doesn't use any undocumented hacks of Backticks, but it's a bit more cumbersome. If solution #1 works for you, then I'm happy to make this part of the official interface contract for Backticks and I'll add a unit test case to ensure that `Runnner#run` always delegates the parameters to `spawn` without tampering with them.

**Comment by bilby91** [comment]
@xeger Thanks for the quick reply! I was able to make it work using your suggestions. Not sure if this will work long term since I need to add some hacky parsing logic to interpret a user input. Not something that is stressing me too much right now. Probably will revisit this particular issue soon and see if I can help and come up with something more stable :). Will be asking some extra questions in the your `docker-compose` gem :)
