### ISSUE TITLE
Caller is expected to escape arguments

### ISSUE THREAD

**Issue by ryansch** [xeger/backticks#8]
If I pass user supplied data in to a command for backticks to run, I need to first call `Shellwords.escape` on it.  This muddies up the calls.  Any chance of getting escaping support in backticks?

**Comment by xeger** [comment]
That seems like an excellent addition; I'll add it ASAP.

**Comment by xeger** [comment]
On second thought, I'm not sure it's needed.

Backticks uses two different methods to run subprocesses. Relevant docs:
  http://ruby-doc.org/core-1.9.3/Process.html#method-c-spawn
  http://ruby-doc.org/stdlib-1.9.3/libdoc/open3/rdoc/Open3.html#method-c-popen3

Given the way we invoke them, these normally don't spawn an intermediate shell between Ruby and the command. Consider what happens when I `Backticks.run('sleep', 3600)`. In unbuffered mode:
```
$ pstree | grep -A1 ruby
 | |   \-+= 07486 tony ruby bin/console
 | |     \--- 07798 tony sleep 3600
```
In buffered mode:
```
 | |   \-+= 07913 tony ruby bin/console
 | |     \--- 07942 tony sleep 3600
```

No shell to spoof, so nothing to escape. Please let me know if you see evidence otherwise!

Of course, there's also the case where you're deliberately invoking a shell with Backticks. In that case, you should probably be validating the input yourself, but if you'd like I can add a `secure:` option which will escape the args for you.

**Comment by ryansch** [comment]
You make an excellent point.  I'll have a look at this use case on Monday.

**Comment by xeger** [comment]
Verified that there's no escaping concern @ryansch? If so, I'll close this issue out.

**Comment by ryansch** [comment]
Blast from the past!  Closing.
